name: tile-map-proxy-with-proxy

#  `version` is obsolete
# version: '3.4'

services:
  tilemapproxy:
    image: tilemapproxy
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HTTP_PROXY=http://v2ray:10809
      - HTTPS_PROXY=http://v2ray:10809
      - HOST=0.0.0.0
    ports:
      # local:container
      - 3000:3000
    
    restart: always
    depends_on:
      - v2ray

    command: pnpm run node:run

  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    volumes:
      - ./v2.json:/etc/v2ray/config.json
    restart: always
    
    # ports:
      # - 10809:10809
    command: v2ray -config=/etc/v2ray/config.json run


networks:
  default:
    driver: bridge